name: Integración

on:
  workflow_dispatch:
    branches:
    - develop

jobs:
  # 👈 esto faltaba
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: npm ci
    - run: npm run build
    - name: Upload dist
      uses: actions/upload-artifact@v4
      with:
        name: dist
        path: dist

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v4
    - run: npm ci
    - run: npm test

  deploy:
    runs-on: ubuntu-latest
    needs: [ test, build ]
    if: github.ref == 'refs/heads/develop'
    steps:
    - uses: actions/checkout@v4
    - name: Download dist
      uses: actions/download-artifact@v4
      with:
        name: dist
        path: dist
    - name: Desplegar en EC2
      env:
        HOST: ${{ secrets.EC2_HOST }}
        USER: ${{ secrets.EC2_USER }}
        KEY: ${{ secrets.EC2_SSH_KEY }}
      run: |
        echo "$KEY" > key.pem
        chmod 600 key.pem
        echo "Desplegando en $HOST"
        ssh -i key.pem -o StrictHostKeyChecking=no $USER@$HOST "sudo rm -rf /var/www/html/*"
        scp -i key.pem -o StrictHostKeyChecking=no -r dist/* $USER@$HOST:/var/www/html/
        ssh -i key.pem -o StrictHostKeyChecking=no $USER@$HOST "sudo systemctl restart nginx"
        rm key.pem
